.not_scheduled: &not-scheduled
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

lint:code:
  image: python:3.12.0-slim-bookworm@sha256:19a6235339a74eca01227b03629f63b6f5020abc21142436eced6ec3a9839a76
  variables:
    PIP_CACHE_DIR: .cache/pip
    PRE_COMMIT_HOME: .cache/pre-commit
  cache:
    paths:
      - .cache
  stage: test
  before_script: |-
    apt update && apt install -y git
    pip install pre-commit==3.5.0
  script: pre-commit run --all-files prettier
  <<: *not-scheduled

lint:commits:
  image: node:20.9.0-alpine3.18@sha256:8e015de364a2eb2ed7c52a558e9f716dcb615560ffd132234087c10ccc1f2c63
  cache:
    paths:
      - .npm
  stage: test
  # Versions should match pre-commit config
  before_script: npm i -g --cache .npm --prefer-offline commitlint@18.2.0 @commitlint/config-conventional@18.1.0
  script: commitlint --from
  <<: *not-scheduled
