default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/aentwist/pre-commit-mirrors-commitlint
    rev: v19.0.3
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          # renovate: datasource=npm
          - commitlint@19.0.3
          # renovate: datasource=npm
          - "@commitlint/config-conventional@19.0.3"
