default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/aentwist/pre-commit-mirrors-commitlint
    rev: v19.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: &commitlint-additional-dependencies
          #
          # renovate: datasource=npm
          - commitlint@19.4.0
          # renovate: datasource=npm
          - "@commitlint/config-conventional@19.2.2"
      - id: commitlint-all
        stages: [manual]
        additional_dependencies: *commitlint-additional-dependencies
