version: 2.1

.platform: &platform
  docker:
    - image: python:3.12.4-slim-bookworm@sha256:44fa7d815050f3dc43b1d5d50c3f4d19870a83c96301c9653e8cf908ccd7892b
  resource_class: small

.environment: &environment
  environment:
    PIP_CACHE_DIR: .cache/pip
    PRE_COMMIT_HOME: .cache/pre-commit

jobs:
  lint-commits:
    <<: *platform
    <<: *environment
    steps:
      - checkout
      - &restore-cache
        restore_cache: &cache-key
          key: renovate-{{ checksum "requirements.txt" }}-{{ checksum ".pre-commit-config.yaml" }}
      - &install-pre-commit
        run: |
          apt update
          apt install -y git
          pip install -r requirements.txt
      - run: pre-commit run --hook-stage=manual --files .pre-commit-config.yaml commitlint-all
      - &save-cache
        save_cache:
          <<: *cache-key
          paths:
            - .cache

  format:
    <<: *platform
    <<: *environment
    steps:
      - checkout
      - *restore-cache
      - *install-pre-commit
      - run: pre-commit run --all-files prettier
      - *save-cache

workflows:
  lint:
    jobs:
      - lint-commits
      - format
